modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"


[[mods]] #mandatory

modId="mercuria" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Mercuria" #mandatory

logoFile="examplemod.png" #optional

credits="Thanks for this example mod goes to Java" #optional

authors="Love, Cheese and small house plants" #optional

description='''
Mod made specifically for enjoyment purposes.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.mercuria]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[40,)" #mandatory
    
    ordering="NONE"

    side="BOTH"
# Here's another dependency
[[dependencies.mercuria]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
